#-------------------------------------
# Configuraciones Generales del Sitio

baseurl: "" # the subruta del sitio, p.ej. /blog
url: "https://asoesem.github.io" # el hostname base & protocolo del sitio, p.ej. http://example.com


#-------------------------------
# Configuracions para SEO
title: ASOESEM
description: Asociación de Estudiantes de la carrera de la Enseñanza de las Matemáticas de la UNED
logo: "/images/logo-light.png"
locale: "es_CR"

#-------------------------------
# Configuración de Construcción

markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 10
paginate_path: "/blog/page/:num"

timezone: "America/Costa_Rica"

#-------------------------------
# Colecciones

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /articulos/:slug
  authors:
    output: true
    permalink: /autores/:name
  # docs:
  #   output: true
  #   permalink: /documentos/:slug

#-------------------------------
# Rutas de Páginas
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "page"

sass:
  sass_dir: _sass
  style: compressed
