#-------------------------------
# Configuración del Sitio
title: Asoesem
description: Asociación de Estudiantes de Enseñanza de la Matemática
logo: "/images/logo-light.png" # Puedes agregar tu logo. Por ejemplo "/images/logo.svg".
logo_dark: "/images/logo-dark.png"
color_scheme: auto # Puedes escoger tres modos auto, light, y dark. Predeterminado, se fija el modo auto, lo que implica que el usuario puede escoger modos light o dark.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Inicio"
      url: "/"
    # - title: "Blog"
    #   url: "/blog/"
    # - title: "Destacados"
    #   url: "/destacados/"
    # - title: "Autores"
    #   url: "/autores/"
    # - title: "Videos"
    #   url: "/videos/"
    - title: "Comisiones"
      submenu:
      - url: "/cofoma/"
        title: "COFOMA"
      - url: "/cocodi/"
        title: "COCODI"
    - title: "Consultas"
      submenu:
      - url: "/organizacion/"
        title: "Organización"
      - url: "/preguntas-frecuentes/"
        title: "Preguntas Frecuentes"

# Botón de llamada a la acción
cta_button:
  enable: true
  cta_button_link: '/contacto/'
  cta_button_text: Contactar


#-------------------------------------------
# Configuración de la Sección de Heroe
hero:
  enable: true
  hero_title: Reglamentos, Noticias, Artículos, y Consejos.
  hero_description: De la Asociación de Estudiantes de Enseñanza de la Matemática de la Universidad Estatal a Distancia.

#-------------------------------------------
# Configuración de la Sección de Etiquetas

tags_section:
  enable: true
  number_posts: 3 # Para controlar cuantos artículos mostrar bajo cada sección de etiqueta. Fije el valor a un número. Tres es el valor predeterminado.
  number_columns: 3 # Puedes especificar el número de columnas de 1-4 para monitores de alta resolución. De forma predeterminda el tema usa una cuadrícula de tres columnas.
  tags:
    - tag: "reglamentos"
    - tag: "pedagogía"
    #- tag: "geometría"


# Puedes agregar muchas secciones de etiquetas a la página de inicio; cada sección mostrará los artículos mas recientes para cada etiqueta.


#-------------------------------------------
# Configuración de la Sección de Autores
authors_section:
  enable: false
  section_title: Conozca nuestros autores


#-------------------------------------------
# Configuración del Pie de Página
footer_description: Noticiales, artículos recientes y novedades de la Asociación de Estudiantes de Enseñanza de la Matemática de la UNED.


# Social Links
# social:
# - {icon: "twitter", link: "https://twitter.com"}
# - {icon: "facebook", link: "https://facebook.com"}
# - {icon: "codepen", link: "https://codepen.io"}
# - {icon: "pinterest", link: "https://pinterest.com"}
# - {icon: "github", link: "https://github.com"}
# - {icon: "youtube", link: "https://youtube.com"}

# Por ejemplo, para agregar un nuevo enlance al pie de página - {icon: "instagram", link: "https://instagram.com"}
# Otros íconos se pueden encontrar en https://ionicons.com/v4/


#-------------------------------------------
# Configuración del Newsletter
mailchimp_settings:
  enable: false
  mailchimp_title: Recibe noticias interesantes
  mailchimp_description: Suscríbete a nuestro newsletter y te enviaremos los correos electrónicos de las últimas publicaciones.
  mailchimp_identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp_input_text: Tu correo electrónico
  mailchimp_button_text: Subscribirse


#-------------------------------------------
# Contact Settings
contact:
  email: xbjvywev # Add your form_id
  description: Si tienes dudas o consultas no dudes en escribirnos y atenderemos tu mensaje a la mayor brevedad posible. 

# NOTE
# Danto theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.

#-------------------------------------------
# Sección de Comentarios (Disqus)
disqus_identifier: asoesem


#-------------------------------------------
# Google Analytics
google_analytics: G-X8T5QZ0TD4


#-------------------------------------------
# Nombres de los Meses
months:
  - Ene
  - Feb
  - Mar
  - Abr
  - May
  - Jun
  - Jul
  - Ago
  - Sep
  - Oct
  - Nov
  - Dec
