# Configuración para el despliegue del sitio
name: Despliega el sitio en GitHub Pages

on:
  # Determina la rama principal de código a desplegar
  push:
    branches: ["main"]

  # Permite ejecutar este workflow desde la pestaña de Acciones de Github
  workflow_dispatch:

# Estable permision del GITHUB_TOKEN para permitir el despliegue a GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permitir solo un despliegue simultáneo, omitiendo las ejecuciones en cola entre la ejecución en curso y la última en cola.
# Sin embargo, NO cancele las ejecuciones en curso, ya que queremos permitir que se el despliegue a producción.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Trabajo de construcción
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configura Ruby
        uses: ruby/setup-ruby@v1.224.0
        with:
          # ruby-version: '3.1' # no se necesita con un archivo .ruby-version
          bundler-cache: true # mantiene las gemas instaladas en una cache automáticamente
          cache-version: 0    # incrementar este número si hace falta refrescar gemas en la cache
      - name: Configura Pages
        uses: actions/configure-pages@v5
      - name: Construye con Jekyll
        # Salida al directorio './_site' de forma predeterminada
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Subir artefacto
        # Automaticamente sube un artefacto de el directorio './_site' de forma predeterminada
        uses: actions/upload-pages-artifact@v3

  # Trabajo de despliegue del sitio
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4